//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bike
    {
        public int BikeID { get; set; }
        public Nullable<int> CID { get; set; }
        [Required]
        public string BikeType { get; set; }
        [Required]
        public Nullable<decimal> BikeModel { get; set; }
        [Required]
        public Nullable<decimal> BikeRecipet { get; set; }
    
        public virtual Sign Sign { get; set; }
    }
}
