//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Car
    {
        public int CarID { get; set; }
        public Nullable<int> CID { get; set; }
        [Required]
        public string CarType { get; set; }
        [Required]
        public string Color { get; set; }
        [Required]
        public Nullable<decimal> CarLiceinse { get; set; }
        [Required]

        public Nullable<decimal> Model { get; set; }
        [Required]
        public string CaseNo { get; set; }
        [Required]
        public string Engine { get; set; }
    
        public virtual Sign Sign { get; set; }
    }
}
