//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TCarDBEntities1 : DbContext
    {
        public TCarDBEntities1()
            : base("name=TCarDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bike> Bikes { get; set; }
        public virtual DbSet<Bike_Operation> Bike_Operation { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Car_Operation> Car_Operation { get; set; }
        public virtual DbSet<Motorcycle> Motorcycles { get; set; }
        public virtual DbSet<Motorcycle_Operation> Motorcycle_Operation { get; set; }
        public virtual DbSet<Sign> Signs { get; set; }
    }
}
